sequenceDiagram
  autonumber
  participant WebID as End-User's WebID Document
  participant OP as OpenID Provider
  participant C as Client
  participant RS as Resource Server
  participant AS as Authorization Server
  C ->> RS: unauthenticated request
  RS ->> C: 401 with a WWW-Authenticate HTTP header
  C ->> OP: start Authorization Code grant
  OP ->> C: return Authorization Code
  C ->> OP: present Authorization Code and DPoP proof
  OP ->> C: return DPoP bound OIDC ID Token
  C ->> AS: request Access Token and push solid Claim Token (including ID Token)
  AS ->> WebID: get WebID document to verify OIDC Issuer
  WebID ->> AS: WebID document
  AS ->> OP: get OP's public key to verify ID Token (JWS)
  OP ->> AS: JWKS
  AS ->> C: if all checks pass issue Access Token
  C ->> RS: request with Access Token
  RS ->> C: representation
