sequenceDiagram
    note over RP: 1. An AJAX request is initiated
    note over RP: 2. Creates a DPoP header token
    RP->>Bob's Pod (RS): 3. Sends Request
    note over Bob's Pod (RS): 4. Checks Access token expirations
    note over Bob's Pod (RS): 5. Checks DPoP Token url and method
    note over Bob's Pod (RS): 5.1. (Optional) Checks DPoP token unique identifier
    note over Bob's Pod (RS): 6. Checks DPoP signature against Access Token
    Bob's Pod (RS)->>Alice's Pod (RS): 7. Retrieves Profile
    Alice's Pod (RS)->>Bob's Pod (RS): Profile
    note over Bob's Pod (RS): 8. Checks Issuer
    Bob's Pod (RS)->>Alice's OP: 9. Retrieves OP configuration
    Alice's OP->>Bob's Pod (RS): OP configuration
    Bob's Pod (RS)->>Alice's OP: 10. Requests JWKS
    Alice's OP->>Bob's Pod (RS): JWKS
    note over Bob's Pod (RS): 11. Checks access token signature validity
    note over Bob's Pod (RS): 12. Performs Authorization
    Bob's Pod (RS)->>RP: 13. Returns Result