sequenceDiagram
  participant WebID as 👩 End-User's WebID Document
  participant OP as 👩 OpenID Provider
  participant ClientID as ⚙️ Client's ID Document
  participant Client as ⚙️ Client
  note over Client: 1. Alice uses the decentphotos app
  note over Client: 2. Alice selects her OP or WebID
  Client->>WebID: 2.1 Retrieve Profile
  WebID->>Client: WebID Profile
  Client->>OP: 3. Retrieves OP configuration
  OP->>Client: OP configuration
  note over Client: 4. Generates PKCE code verifier and code challenge
  note over Client: 5. Saves code verifier to session storage
  Client->>OP: 6. Authorization Request
  OP->>ClientID: 7. Fetch Client ID Document
  ClientID->>OP: ClientID Profile
  note over OP: 8. Validates redirect url with WebID
  note over OP: 9. Alice Logs In
  note over OP: 10. Generates an authorization code
  OP->>Client: 11. Send authorization code to redirect url
  note over Client: 12. Generates DPoP Client Key Pair
  note over Client: 13. Generates a DPoP Header
  Client->>OP: 14. Token request with code and code verifier
  note over OP: 15. Validates code verifier
  note over OP: 16. Validates DPoP Token signature
  note over OP: 17. Converts the DPoP public key to a JWK thumbprint
  note over OP: 19. Generates id token
  note over OP: 20. Generates refresh token
  OP->>Client: 21. Send tokens
