# Workflow for moving the editor's draft into published form

name: Format as CG Draft
on:
  push:
    tags:
      - solid-oidc-draft-[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install Bikeshed
        run: |
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: Adjust document status to CG-DRAFT
        run: |
          sed -i 's|w3c/ED|w3c/CG-DRAFT|g' index.bs
          sed -i 's|w3c/ED|w3c/CG-DRAFT|g' primer/index.bs

      - name: Generate HTML
        run: for bsdoc in ./*.bs ./**/*.bs; do bikeshed spec $bsdoc; done

      - name: Generate SVG
        run: for diagram in ./*.mmd primer/*.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done

      - name: Create publication
        run: |
          mkdir publish
          mv index.html ./publish/oidc.html
          mv solid.svg ./publish/solid.svg
          mv sequence.mmd.svg ./publish/oidc-sequence.svg
          sed -i 's/sequence.mmd.svg/oidc-sequence.svg/g' ./publish/oidc.html
          sed -i 's|https://solid.github.io/solid-oidc/solid.svg|https://solidproject.org/TR/solid.svg|g' ./publish/oidc.html
          sed -i 's|https://solid.github.io/solid-oidc/primer/|https://solidproject.org/TR/oidc-primer|g' ./publish/oidc.html
          sed -i 's|https://solid.github.io/solid-oidc/|https://solidproject.org/TR/oidc|g' ./publish/oidc.html

          mv primer/index.html ./publish/oidc-primer.html
          mv primer/primer-login.mmd.svg ./publish/oidc-primer-login.svg
          mv primer/primer-request.mmd.svg ./publish/oidc-primer-request.svg
          sed -i 's/primer-login.mmd.svg/oidc-primer-login.svg/g' ./publish/oidc-primer.html
          sed -i 's/primer-request.mmd.svg/oidc-primer-request.svg/g' ./publish/oidc-primer.html
          sed -i 's|https://solid.github.io/solid-oidc/primer/|https://solidproject.org/TR/oidc-primer|g' ./publish/oidc-primer.html
          sed -i 's|https://solid.github.io/solid-oidc/|https://solidproject.org/TR/oidc|g' ./publish/oidc-primer.html

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish
          publish_branch: solid-tr-publication
          personal_token: ${{ secrets.GITHUB_TOKEN }}

